# Generated by Django 2.2.2 on 2020-08-28 17:51

from django.db import migrations, models
import django.db.models.deletion
import kbde.django.db_import.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('kbde_django_bg_process', '0004_auto_20200820_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ImportFile',
            fields=[
                ('bgprocessmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kbde_django_bg_process.BgProcessModel')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('source', models.FileField(upload_to=kbde.django.db_import.models.get_source_upload_to)),
            ],
            bases=('kbde_django_bg_process.bgprocessmodel',),
        ),
        migrations.CreateModel(
            name='ImportMapping',
            fields=[
                ('bgprocessmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kbde_django_bg_process.BgProcessModel')),
                ('import_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kbde_django_db_import.ImportFile')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_kbde_django_db_import.importmapping_set+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('kbde_django_bg_process.bgprocessmodel', models.Model),
        ),
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kbde_django_db_import.ImportFile')),
            ],
        ),
        migrations.CreateModel(
            name='ImportValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kbde_django_db_import.ImportColumn')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kbde_django_db_import.ImportRow')),
            ],
        ),
        migrations.CreateModel(
            name='ImportMappingRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('status_message', models.CharField(blank=True, max_length=255)),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kbde_django_db_import.ImportMapping')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kbde_django_db_import.ImportRow')),
            ],
        ),
        migrations.CreateModel(
            name='ImportMappingColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_field', models.CharField(max_length=255)),
                ('is_identifier', models.BooleanField(default=False, help_text='Should this column be used to look up an existing model?')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kbde_django_db_import.ImportColumn')),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kbde_django_db_import.ImportMapping')),
            ],
        ),
        migrations.AddField(
            model_name='importcolumn',
            name='import_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kbde_django_db_import.ImportFile'),
        ),
    ]
