# Generated by Django 2.2.2 on 2020-08-28 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kbde_django_bg_process', '0004_auto_20200820_1710'),
        ('kbde_django_db_import', '0002_importmappingrow_new_instance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Import',
            fields=[
                ('bgprocessmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kbde_django_bg_process.BgProcessModel')),
                ('import_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kbde_django_db_import.ImportMapping')),
            ],
            bases=('kbde_django_bg_process.bgprocessmodel',),
        ),
    ]
