# Generated by Django 2.2.2 on 2020-08-31 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kbde_django_db_import', '0003_import'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='importmappingcolumn',
            unique_together={('import_field', 'column')},
        ),
    ]
