# Generated by Django 2.2.2 on 2020-08-31 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kbde_django_db_import', '0004_auto_20200831_1842'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='importmappingcolumn',
            unique_together={('mapping', 'import_field', 'column')},
        ),
    ]
