# Generated by Django 2.2.5 on 2019-09-30 02:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=255)),
                ('required', models.BooleanField(default=True)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('label_suffix', models.CharField(blank=True, max_length=255)),
                ('initial', models.CharField(blank=True, max_length=255)),
                ('help_text', models.CharField(blank=True, max_length=255)),
                ('localize', models.BooleanField(default=False)),
                ('disabled', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.UUIDField(default=uuid.uuid4)),
                ('title', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BooleanField',
            fields=[
                ('field_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kbde_django_db_forms.Field')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('kbde_django_db_forms.field',),
        ),
        migrations.CreateModel(
            name='CharField',
            fields=[
                ('field_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kbde_django_db_forms.Field')),
                ('max_length', models.IntegerField(blank=True, default=None, null=True)),
                ('min_length', models.IntegerField(blank=True, default=None, null=True)),
                ('strip', models.BooleanField(default=True)),
                ('empty_value', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('kbde_django_db_forms.field',),
        ),
        migrations.CreateModel(
            name='ChoiceField',
            fields=[
                ('field_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kbde_django_db_forms.Field')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('kbde_django_db_forms.field',),
        ),
        migrations.CreateModel(
            name='DateField',
            fields=[
                ('field_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kbde_django_db_forms.Field')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('kbde_django_db_forms.field',),
        ),
        migrations.CreateModel(
            name='DateTimeField',
            fields=[
                ('field_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kbde_django_db_forms.Field')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('kbde_django_db_forms.field',),
        ),
        migrations.CreateModel(
            name='DecimalField',
            fields=[
                ('field_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kbde_django_db_forms.Field')),
                ('max_value', models.IntegerField(blank=True, default=None, null=True)),
                ('min_value', models.IntegerField(blank=True, default=None, null=True)),
                ('max_digits', models.IntegerField(blank=True, default=None, null=True)),
                ('decimal_places', models.IntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('kbde_django_db_forms.field',),
        ),
        migrations.CreateModel(
            name='DurationField',
            fields=[
                ('field_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kbde_django_db_forms.Field')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('kbde_django_db_forms.field',),
        ),
        migrations.CreateModel(
            name='EmailField',
            fields=[
                ('field_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kbde_django_db_forms.Field')),
                ('max_length', models.IntegerField(blank=True, default=None, null=True)),
                ('min_length', models.IntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('kbde_django_db_forms.field',),
        ),
        migrations.CreateModel(
            name='FileField',
            fields=[
                ('field_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kbde_django_db_forms.Field')),
                ('max_length', models.IntegerField(blank=True, default=None, null=True)),
                ('allow_empty_file', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('kbde_django_db_forms.field',),
        ),
        migrations.CreateModel(
            name='FloatField',
            fields=[
                ('field_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kbde_django_db_forms.Field')),
                ('max_value', models.IntegerField(blank=True, default=None, null=True)),
                ('min_value', models.IntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('kbde_django_db_forms.field',),
        ),
        migrations.CreateModel(
            name='GenericIpAddressField',
            fields=[
                ('field_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kbde_django_db_forms.Field')),
                ('protocol', models.CharField(choices=[('both', 'Both'), ('IPv4', 'IPv4'), ('IPv6', 'IPv6')], max_length=255)),
                ('unpack_ipv4', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('kbde_django_db_forms.field',),
        ),
        migrations.CreateModel(
            name='ImageField',
            fields=[
                ('field_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kbde_django_db_forms.Field')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('kbde_django_db_forms.field',),
        ),
        migrations.CreateModel(
            name='IntegerField',
            fields=[
                ('field_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kbde_django_db_forms.Field')),
                ('max_value', models.IntegerField(blank=True, default=None, null=True)),
                ('min_value', models.IntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('kbde_django_db_forms.field',),
        ),
        migrations.CreateModel(
            name='NullBooleanField',
            fields=[
                ('field_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kbde_django_db_forms.Field')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('kbde_django_db_forms.field',),
        ),
        migrations.CreateModel(
            name='RegexField',
            fields=[
                ('field_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kbde_django_db_forms.Field')),
                ('regex', models.CharField(blank=True, max_length=255)),
                ('max_length', models.IntegerField(blank=True, default=None, null=True)),
                ('min_length', models.IntegerField(blank=True, default=None, null=True)),
                ('strip', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('kbde_django_db_forms.field',),
        ),
        migrations.CreateModel(
            name='SlugField',
            fields=[
                ('field_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kbde_django_db_forms.Field')),
                ('allow_unicode', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('kbde_django_db_forms.field',),
        ),
        migrations.CreateModel(
            name='TimeField',
            fields=[
                ('field_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kbde_django_db_forms.Field')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('kbde_django_db_forms.field',),
        ),
        migrations.CreateModel(
            name='UrlField',
            fields=[
                ('field_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kbde_django_db_forms.Field')),
                ('max_length', models.IntegerField(blank=True, default=None, null=True)),
                ('min_length', models.IntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('kbde_django_db_forms.field',),
        ),
        migrations.CreateModel(
            name='UuidField',
            fields=[
                ('field_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kbde_django_db_forms.Field')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('kbde_django_db_forms.field',),
        ),
        migrations.CreateModel(
            name='FilledForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.UUIDField(default=uuid.uuid4)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kbde_django_db_forms.Form')),
            ],
        ),
        migrations.CreateModel(
            name='FieldValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kbde_django_db_forms.Field')),
                ('filled_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kbde_django_db_forms.FilledForm')),
            ],
        ),
        migrations.AddField(
            model_name='field',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kbde_django_db_forms.Form'),
        ),
        migrations.AddField(
            model_name='field',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_kbde_django_db_forms.field_set+', to='contenttypes.ContentType'),
        ),
        migrations.CreateModel(
            name='MultipleChoiceField',
            fields=[
                ('choicefield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kbde_django_db_forms.ChoiceField')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('kbde_django_db_forms.choicefield',),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('choice_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kbde_django_db_forms.ChoiceField')),
            ],
        ),
    ]
