# Generated by Django 2.2.5 on 2019-09-30 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kbde_django_db_forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kbde_django_db_forms.Form')),
            ],
        ),
        migrations.AddField(
            model_name='field',
            name='field_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kbde_django_db_forms.FieldGroup'),
        ),
    ]
