# Generated by Django 2.2.5 on 2019-09-30 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_forms', '0002_auto_20190930_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='priority',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
