# Generated by Django 2.2.5 on 2019-09-30 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_forms', '0003_choice_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
