# Generated by Django 2.2.5 on 2019-09-30 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_forms', '0004_auto_20190930_0435'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldgroup',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
