# Generated by Django 3.2.10 on 2022-05-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbde_django_db_forms', '0007_auto_20220515_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='filledform',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='filledform',
            name='time_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
