# Generated by Django 3.2.12 on 2022-07-23 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbde_django_db_forms', '0008_auto_20220515_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
