# Generated by Django 3.2.2 on 2021-05-31 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbde_django_token_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authtoken',
            name='expire_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
