# Generated by Django 3.2.7 on 2021-09-04 20:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kbde_django_token_auth', '0002_authtoken_expire_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='time_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
