# Generated by Django 3.1 on 2020-08-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbde_django_bg_process', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bgprocessmodel',
            name='bg_process_id',
            field=models.IntegerField(null=True),
        ),
    ]
