# Generated by Django 3.1 on 2020-08-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbde_django_bg_process', '0003_auto_20200820_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bgprocessmodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='bgprocessmodel',
            name='bg_process_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
