# Generated by Django 3.2.12 on 2023-04-13 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbde_django_bg_process', '0005_bgprocessmodel_bg_process_exception'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bgprocessmodel',
            name='bg_process_exception',
            field=models.TextField(blank=True),
        ),
    ]
