# Generated by Django 3.1.1 on 2021-05-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbde_django_login_link', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginlink',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
