# Generated by Django 3.1.1 on 2021-05-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbde_django_login_link', '0002_loginlink_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginlink',
            name='confirmed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
