# Generated by Django 3.1.1 on 2021-05-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbde_django_login_link', '0003_auto_20210518_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginlink',
            name='confirmed',
            field=models.BooleanField(null=True),
        ),
    ]
