# Generated by Django 2.2.2 on 2020-08-05 18:38

from django.db import migrations, models
import django.db.models.deletion
import kbde.django.report.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('kbde_django_bg_process', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('bgprocessmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kbde_django_bg_process.BgProcessModel')),
                ('name', models.CharField(max_length=255)),
                ('record_count', models.IntegerField(blank=True, null=True)),
                ('renderer_name', models.CharField(max_length=255)),
                ('records_complete', models.IntegerField(default=0)),
                ('result', models.FileField(blank=True, null=True, upload_to=kbde.django.report.models.get_report_upload_to)),
                ('time_started', models.DateTimeField(blank=True, null=True)),
                ('time_completed', models.DateTimeField(blank=True, null=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_kbde_django_report.report_set+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('kbde_django_bg_process.bgprocessmodel', models.Model),
        ),
    ]
