# Generated by Django 2.2.5 on 2020-01-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=255)),
                ('code', models.CharField(blank=True, max_length=255)),
                ('location_type', models.IntegerField(choices=[(1, 'Country'), (2, 'State'), (3, 'County'), (4, 'Municipality'), (5, 'Ward'), (6, 'Voting District')])),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('parents', models.ManyToManyField(blank=True, related_name='children', to='kbde_django_location.Location')),
            ],
            options={
                'unique_together': {('name', 'code', 'location_type')},
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_1', models.CharField(db_index=True, max_length=255)),
                ('street_2', models.CharField(blank=True, db_index=True, max_length=255)),
                ('street_3', models.CharField(blank=True, db_index=True, max_length=255)),
                ('city', models.CharField(db_index=True, max_length=255)),
                ('state', models.CharField(db_index=True, max_length=255)),
                ('zip_code', models.CharField(db_index=True, max_length=255)),
                ('zip_code_last_4', models.CharField(db_index=True, max_length=255)),
                ('country', models.CharField(blank=True, db_index=True, max_length=255)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('locations', models.ManyToManyField(to='kbde_django_location.Location')),
            ],
            options={
                'unique_together': {('street_1', 'street_2', 'street_3', 'city', 'state', 'zip_code', 'country')},
            },
        ),
    ]
