# Generated by Django 2.2.5 on 2020-01-31 18:35

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kbde_django_location', '0002_auto_20200102_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
