# Generated by Django 2.2.5 on 2020-01-31 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kbde_django_location', '0003_point_point'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='point',
            unique_together={('name', 'point')},
        ),
        migrations.RemoveField(
            model_name='point',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='point',
            name='longitude',
        ),
    ]
