# Generated by Django 3.1 on 2020-08-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbde_django_location', '0004_auto_20200131_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='point_id',
            field=models.IntegerField(null=True),
        ),
    ]
