# Generated by Django 3.1 on 2020-08-20 16:46

from django.db import migrations, models


def update_id_field(apps, schema_editor):
    Point = apps.get_model("kbde_django_location", "Point")
    Point.objects.update(point_id=models.F("id"))

class Migration(migrations.Migration):

    dependencies = [
        ('kbde_django_location', '0005_point_point_id'),
    ]

    operations = [
        migrations.RunPython(update_id_field),
    ]
