# Generated by Django 3.1 on 2020-08-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbde_django_location', '0007_auto_20200820_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='location_id',
            field=models.IntegerField(null=True),
        ),
    ]
