# Generated by Django 3.1 on 2020-08-20 17:00

from django.db import migrations, models


def update_id_fields(apps, schema_editor):
    Address = apps.get_model("kbde_django_location", "Address")
    Address.objects.update(address_id=models.F("id"))

    Location = apps.get_model("kbde_django_location", "Location")
    Location.objects.update(location_id=models.F("id"))


class Migration(migrations.Migration):

    dependencies = [
        ('kbde_django_location', '0008_auto_20200820_1700'),
    ]

    operations = [
        migrations.RunPython(update_id_fields),
    ]
