# Generated by Django 3.1 on 2020-08-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbde_django_location', '0009_auto_20200820_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='id',
        ),
        migrations.RemoveField(
            model_name='location',
            name='id',
        ),
        migrations.AlterField(
            model_name='address',
            name='address_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
