# Generated by Django 3.1 on 2020-08-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbde_django_location', '0011_auto_20200820_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='locations',
            field=models.ManyToManyField(blank=True, to='kbde_django_location.Location'),
        ),
        migrations.AlterField(
            model_name='point',
            name='locations',
            field=models.ManyToManyField(blank=True, to='kbde_django_location.Location'),
        ),
    ]
