# Generated by Django 3.1 on 2020-08-20 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kbde_django_location', '0012_auto_20200820_1956'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='point',
            unique_together=set(),
        ),
    ]
