# Generated by Django 3.1.2 on 2020-10-26 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbde_django_location', '0016_auto_20201024_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city_slug',
            field=models.SlugField(blank=True, db_index=False, max_length=255),
        ),
        migrations.AddField(
            model_name='address',
            name='country_slug',
            field=models.SlugField(blank=True, db_index=False, max_length=255),
        ),
        migrations.AddField(
            model_name='address',
            name='state_slug',
            field=models.SlugField(blank=True, db_index=False, max_length=255),
        ),
        migrations.AddField(
            model_name='address',
            name='street_1_slug',
            field=models.SlugField(blank=True, db_index=False, max_length=255),
        ),
        migrations.AddField(
            model_name='address',
            name='street_2_slug',
            field=models.SlugField(blank=True, db_index=False, max_length=255),
        ),
        migrations.AddField(
            model_name='address',
            name='street_3_slug',
            field=models.SlugField(blank=True, db_index=False, max_length=255),
        ),
    ]
