# Generated by Django 3.1.2 on 2020-10-26 03:49

from django.db import migrations
from django import utils


def set_address_slugs(apps, schema_editor):
    Address = apps.get_model("kbde_django_location", "Address")

    for a in Address.objects.all():
        for field_name in [
            "street_1",
            "street_2",
            "street_3",
            "city",
            "state",
            "country",
        ]:
            value = getattr(a, field_name)
            slug = utils.text.slugify(value)
            setattr(a, f"{field_name}_slug", slug)

        a.save()


class Migration(migrations.Migration):

    dependencies = [
        ('kbde_django_location', '0017_auto_20201026_0348'),
    ]

    operations = [
        migrations.RunPython(set_address_slugs)
    ]
